Repository dotnet/samples, pull requests merged in 2018-11, with the labels that each got.

#417 Removed Environment.OSVersion examples
  snippets/cpp/VS_Snippets_CLR/Environment.OSVersion/CPP/osversion.cpp
  snippets/csharp/VS_Snippets_CLR/Environment.OSVersion/CS/osversion.cs
  snippets/visualbasic/VS_Snippets_CLR/Environment.OSVersion/VB/osversion.vb
Labels: :construction: Hold for related PR

#433 Added sample code for KeyPress events
  snippets/csharp/VS_Snippets_Winforms/Control.KeyDown/CS/Form2.cs
  snippets/visualbasic/VS_Snippets_Winforms/Control.KeyDown/VB/Form2.vb
Labels: :sparkles: 1st-time docs contributor!, changes-addressed

#437 Deleted CultureTypes examples removed from documentation
  snippets/cpp/VS_Snippets_CLR_System/system.globalization.cultureTypes/cpp/ct.cpp
  snippets/csharp/VS_Snippets_CLR_System/system.globalization.cultureTypes/cs/getcultures3.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.globalization.cultureTypes/vb/getcultures3.vb
Labels: :construction: Hold for related PR

#459 port changes
  snippets/csharp/VS_Snippets_VBCSharp/csasyncexceptions/cs/class1.cs
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsAccess/CS/csrefKeywordsAccess.cs
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsExceptions/CS/csrefKeywordsExceptions.cs
Labels: :file_folder: Repo - samples, migration-fixes

#464 Use simplified `float` syntax.
  snippets/cpp/VS_Snippets_CLR_System/system.Collections.Hashtable_ctorDictionaryFloat/CPP/hashtable_ctordictionaryfloat.cpp
  snippets/cpp/VS_Snippets_CLR_System/system.Collections.Hashtable_ctorIntFloat/CPP/hashtable_ctorintfloat.cpp
  snippets/csharp/VS_Snippets_CLR_System/system.Collections.Hashtable_ctorDictionaryFloat/CS/hashtable_ctordictionaryfloat.cs
  snippets/csharp/VS_Snippets_CLR_System/system.Collections.Hashtable_ctorIntFloat/CS/hashtable_ctorintfloat.cs
  snippets/csharp/VS_Snippets_Misc/astoria northwind service/cs/northwind2.svc.cs
  snippets/csharp/VS_Snippets_VBCSharp/VbPowerPacksShapeScale/CS/ShapeScale.cs
  snippets/csharp/VS_Snippets_Winforms/TabControl.RightAlignedTabs/CS/Form1.cs
Labels: :sparkles: 1st-time docs contributor!

#469 Clarification for "Working with LINQ" tutorial
  csharp/getting-started/console-linq/Program.cs
  csharp/getting-started/console-linq/extensions.cs
Labels: :sparkles: 1st-time docs contributor!

#462 C# Strings - Code Snippets
  snippets/csharp/programming-guide/strings/Strings_1.cs
  snippets/csharp/programming-guide/strings/Strings_1.csproj
Labels: :sparkles: 1st-time docs contributor!
