Repository dotnet/samples, pull requests merged in 2018-12, with the labels that each got.

#486 Updates inline comments to specify correct output.
  snippets/csharp/concepts/structs/literals.cs
Labels: :sparkles: 1st-time docs contributor!

#508 fixes dotnet/docs#8941
  snippets/csharp/programming-guide/classes-and-structs/properties-1.cs
  snippets/csharp/programming-guide/classes-and-structs/properties-2.cs
  snippets/csharp/programming-guide/classes-and-structs/properties-3.cs
Labels: :sparkles: 1st-time GH contributor!

#513 Fixed typo
  snippets/cpp/VS_Snippets_Winforms/TreeNode_ForeColor/CPP/treenode_forecolor.cpp
  snippets/csharp/VS_Snippets_Winforms/TreeNode_ForeColor/CS/treenode_forecolor.cs
  snippets/visualbasic/VS_Snippets_Winforms/TreeNode_ForeColor/VB/treenode_forecolor.vb
Labels: :sparkles: 1st-time samples contributor!
