Repository dotnet/samples, pull requests merged in 2018-05, with the labels that each got.

#37 Fixed sample and made it easier to understand
  snippets/csharp/VS_Snippets_Winforms/Classic OpenFileDialog Example/CS/source.cs
Labels: :sparkles: 1st-time docs contributor!

#55 Dispose enumerators in custom sequence (LINQ) sample
  core/linq/csharp/customsequence/CustomSequence-Sample-1.cs
Labels: :sparkles: 1st-time docs contributor!

#59 Fix small formatting errors in inheritance sample
  snippets/csharp/tutorials/inheritance/base-and-derived.cs
Labels: :sparkles: 1st-time docs contributor!

#56 Added examples for What's new in .NET Core 2.1
  core/whats-new/whats-new-in-21/cs/Program.cs
  core/whats-new/whats-new-in-21/cs/brotli.cs
  core/whats-new/whats-new-in-21/cs/whats-new.csproj
  core/whats-new/whats-new-in-21/vb/brotli.vb
  core/whats-new/whats-new-in-21/vb/whats-new.vbproj
Labels: :file_folder: Repo - samples, P0

#54 Create .editorconfig
  .editorconfig
Labels: :file_folder: Repo - samples

#60 Delete examples removed from documentation
  snippets/cpp/VS_Snippets_CLR_System/system.Threading.Interlocked.Exchange/CPP/source.cpp
  snippets/csharp/VS_Snippets_CLR_System/system.Threading.Interlocked.Exchange/CS/Exchange5.cs
  snippets/csharp/VS_Snippets_CLR_System/system.Threading.Interlocked.Exchange/CS/source.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.Threading.Interlocked.Exchange/VB/Exchange5.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.Threading.Interlocked.Exchange/VB/source.vb
Labels: :construction: Hold for related PR, :file_folder: Repo - samples

#86 Added do and while code snippets
  snippets/csharp/keywords/IterationKeywordsExamples.cs
Labels: :construction: Hold for related PR

#85 Added Span<T>.Enumerator examples
  snippets/csharp/api/system/span.enumerator/nosync/Program.cs
  snippets/csharp/api/system/span.enumerator/nosync/synchronization.csproj
  snippets/csharp/api/system/span.enumerator/sync/Program.cs
  snippets/csharp/api/system/span.enumerator/sync/synchronization.csproj
Labels: changes-addressed

#91 Update AsyncSocketServer.cs
  snippets/csharp/VS_Snippets_Remoting/NCLAsyncSocketServer/CS/AsyncSocketServer.cs
Labels: :sparkles: 1st-time docs contributor!

#88 Update source.cs
  snippets/csharp/VS_Snippets_ADO.NET/DataWorks DataTable.CreateDataReader/CS/source.cs
Labels: :sparkles: 1st-time docs contributor!
