Repository dotnet/samples, pull requests merged in 2018-08, with the labels that each got.

#212 Better example for Assembly.GetCallingAssembly
  snippets/csharp/VS_Snippets_CLR_System/system.Reflection.Assembly/CS/getcallingassembly1.cs
Labels: :sparkles: 1st-time docs contributor!

#217 removed code snippet tags
  snippets/csharp/VS_Snippets_Wpf/BusinessLayerValidation/CSharp/Window1.xaml
Labels: :construction: Hold for related PR

#222 Update README
  core/console-apps/NewTypesMsBuild/README.md
Labels: :sparkles: 1st-time docs contributor!

#232 update to ML.NET 0.4
  machine-learning/tutorials/IrisClustering/IrisClustering.csproj
  machine-learning/tutorials/SentimentAnalysis/SentimentAnalysis.csproj
Labels: :file_folder: Repo - samples

#244 port changes done in inner snippet
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsNamespace/CS/csrefKeywordsNamespace.cs
Labels: :file_folder: Repo - samples, migration-fixes

#245 removing empty lines
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsOperator/CS/csrefKeywordsOperators.cs
Labels: :file_folder: Repo - samples

#252 Correct Box C# example
  snippets/csharp/VS_Snippets_CLR_System/system.collections.generic.iequalitycomparer/cs/program.cs
Labels: :sparkles: 1st-time docs contributor!

#266 Modifying order of the case clauses
  snippets/csharp/language-reference/keywords/when/when.cs
Labels: :sparkles: 1st-time docs contributor!

#264 remove unneeded new lines and fix indentation
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsModifiers/CS/csrefKeywordsModifiers.cs
Labels: :file_folder: Repo - samples

#273 Update example2.cs
  snippets/csharp/VS_Snippets_CLR/dg_exceptionDesign/cs/example2.cs
Labels: :sparkles: 1st-time docs contributor!

#269 update nunit project
  core/getting-started/unit-testing-using-nunit/PrimeService.Tests/PrimeService.Tests.csproj
  core/getting-started/unit-testing-using-nunit/PrimeService.Tests/PrimeService_IsPrimeShould.cs
  core/getting-started/unit-testing-using-nunit/PrimeService/PrimeService.cs
Labels: :file_folder: Repo - samples

#270 remove unneeded lines
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsJump/CS/csrefKeywordsJump.cs
Labels: :file_folder: Repo - samples
