Repository dotnet/samples, pull requests merged in 2018-10, with the labels that each got.

#333 Updating readme for dotnet samples for linq/csharp
  core/linq/csharp/README.md
Labels: :sparkles: 1st-time docs contributor!

#336 Removed redundant Attribute suffix
  snippets/cpp/VS_Snippets_CLR_System/system.Threading.Thread.DoNotUseDataSlots/CPP/source.cpp
  snippets/csharp/VS_Snippets_CLR_System/system.Threading.Thread.DoNotUseDataSlots/CS/source.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.Threading.Thread.DoNotUseDataSlots/vb/source.vb
Labels: :sparkles: 1st-time docs contributor!

#348 update package version and add snippet tag
  core/getting-started/unit-testing-vb-nunit/PrimeService.Tests/PrimeService.Tests.vbproj
Labels: :file_folder: Repo - samples

#351 add Memory<T> for VB.Net sample
  core/whats-new/whats-new-in-21/vb/Program.vb
Labels: :sparkles: 1st-time docs contributor!

#355 Add multithreading to ConcurrentBag example
  snippets/csharp/api/system.collections.concurrent/concurrentbag/concbag.cs
  snippets/visualbasic/api/systems.collections.concurrent/concurrentbag/concbag.vb
Labels: :sparkles: 1st-time docs contributor!

#368 Fix typo: Calcualtor -> Calculator
  csharp/unit-testing-best-practices/after/StringCalculatorTests.cs
Labels: :sparkles: 1st-time docs contributor!

#367 Update README.md
  README.md
Labels: :sparkles: 1st-time docs contributor!

#359 Add ListBox ScrollIntoView snippet
  snippets/csharp/VS_Snippets_Wpf/ListBox_snip/CSharp/Window1.xaml
  snippets/csharp/VS_Snippets_Wpf/ListBox_snip/CSharp/Window1.xaml.cs
  snippets/visualbasic/VS_Snippets_Wpf/ListBox_snip/visualbasic/window1.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ListBox_snip/visualbasic/window1.xaml.vb
Labels: :sparkles: 1st-time docs contributor!

#373 removed extra spaces
  core/getting-started/golden/library/Thing.cs
  core/getting-started/golden/test-library/UnitTest1.cs
Labels: :sparkles: 1st-time docs contributor!

#356 Revise ConcurrentStack examples
  snippets/csharp/VS_Snippets_CLR_System/system.collections.concurrent.concurrentstack/cs/concstack.cs
  snippets/csharp/VS_Snippets_CLR_System/system.collections.concurrent.concurrentstack/cs/concstack_range.cs
  snippets/csharp/VS_Snippets_CLR_System/system.collections.concurrent.concurrentstack/cs/concstack_single.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.collections.concurrent.concurrentstack/vb/concstack.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.collections.concurrent.concurrentstack/vb/concstack_range.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.collections.concurrent.concurrentstack/vb/concstack_single.vb
Labels: changes-addressed

#382 Update form1.cs
  snippets/csharp/VS_Snippets_Winforms/System.Drawing.BitmapMembers/CS/form1.cs
Labels: :sparkles: 1st-time docs contributor!

#388 Remove redundant string assignment in File class example
  snippets/csharp/VS_Snippets_CLR/File Class Example/CS/file class example.cs
Labels: :sparkles: 1st-time docs contributor!

#389 update samples related to ref, in, arguments and returns
  csharp/safe-efficient-code/benchmark/Program.cs
  csharp/safe-efficient-code/benchmark/benchmark.csproj
  csharp/safe-efficient-code/ref-readonly-struct/Point3D.cs
  csharp/safe-efficient-code/ref-readonly-struct/Program.cs
  csharp/safe-efficient-code/ref-readonly-struct/ref-readonly-struct.csproj
  csharp/safe-efficient-code/safe-efficient-code.sln
Labels: P1

#404 Added addition operator snippets
  snippets/csharp/language-reference/operators/AdditionExamples.cs
  snippets/csharp/language-reference/operators/Program.cs
Labels: verify-build-before-merge

#397 Fix style in Regex.Replace example
  snippets/csharp/VS_Snippets_CLR/Regex.Replace-Instance/cs/sample.cs
  snippets/visualbasic/VS_Snippets_CLR/Regex.Replace-Instance/vb/sample.vb
Labels: :sparkles: 1st-time docs contributor!, changes-addressed

#377 Remove unecessary try..catch constructs
  snippets/cpp/VS_Snippets_CLR/Process_GetProcessesByName2_2/CPP/process_getprocessesbyname2_2.cpp
  snippets/cpp/VS_Snippets_CLR/Process_StandardError/CPP/source.cpp
  snippets/cpp/VS_Snippets_CLR_System/system.Security.Permissions.UrlIdentityPermission/CPP/urlidentity.cpp
  snippets/cpp/VS_Snippets_Winforms/ContainerExmpl/CPP/librarycontainer.cpp
  snippets/csharp/VS_Snippets_CLR/Process_GetProcessesByName2_2/CS/process_getprocessesbyname2_2.cs
  snippets/csharp/VS_Snippets_CLR/Process_StandardError/CS/source.cs
  snippets/csharp/VS_Snippets_CLR_System/system.Security.Permissions.UIPermission/CS/uipermission.cs
  snippets/csharp/VS_Snippets_CLR_System/system.Security.Permissions.UrlIdentityPermission/CS/urlidentity.cs
  snippets/csharp/VS_Snippets_CLR_System/system.Security.Permissions.ZoneIdentityPermission/CS/zoneidentity.cs
  snippets/csharp/VS_Snippets_Winforms/ContainerExmpl/CS/librarycontainer.cs
  snippets/visualbasic/VS_Snippets_CLR/Process_GetProcessesByName2_2/VB/process_getprocessesbyname2_2.vb
  snippets/visualbasic/VS_Snippets_CLR/Process_StandardError/VB/source.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.Security.Permissions.UIPermission/VB/uipermission.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.Security.Permissions.UrlIdentityPermission/VB/urlidentity.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.Security.Permissions.ZoneIdentityPermission/VB/zoneidentity.vb
  snippets/visualbasic/VS_Snippets_Winforms/ContainerExmpl/VB/librarycontainer.vb
Labels: changes-addressed

#418 Formatting fixes in README.mds
  core/getting-started/golden/README.md
  core/linq/csharp/README.md
  csharp/expression-trees/README.md
Labels: :sparkles: 1st-time docs contributor!
