Repository dotnet/samples, pull requests merged in 2018-09, with the labels that each got.

#284 Revised deployment topics for .NET Core 2.1
  snippets/core/deploying/cs/deployment-example.cs
  snippets/core/deploying/vb/deployment-example.vb
  snippets/core/deploying/xml/invariant.csproj
Labels: :checkered_flag: Release: .NET Core 2.1

#285 Fix logic comparison (docs issue #7481)
  snippets/csharp/VS_Snippets_Winforms/system.windows.forms.methodinvoker/cs/form1.cs
  snippets/visualbasic/VS_Snippets_Winforms/system.windows.forms.methodinvoker/vb/form1.vb
Labels: :file_folder: Repo - samples

#291 Stream Disposal in StreamReader Constructor Snippet
  snippets/csharp/VS_Snippets_CLR/StrmReader Ctor1/CS/strmreader ctor1.cs
Labels: :sparkles: 1st-time docs contributor!

#248 Add is constant pattern snippet for null check.
  snippets/csharp/language-reference/keywords/is/is-const-pattern11.cs
Labels: :sparkles: 1st-time docs contributor!

#317 Updated example to show the output
  snippets/cpp/VS_Snippets_Data/Classic WebData XmlElement.InnerXml Example/CPP/source.cpp
  snippets/csharp/VS_Snippets_Data/Classic WebData XmlElement.InnerXml Example/CS/source.cs
  snippets/visualbasic/VS_Snippets_Data/Classic WebData XmlElement.InnerXml Example/VB/source.vb
Labels: :sparkles: 1st-time docs contributor!
