Repository dotnet/samples, pull requests merged in 2018-06, with the labels that each got.

#92 HashCode examples
  snippets/csharp/VS_Snippets_CLR_System/system.hashcode.structure/cs/example1.cs
  snippets/csharp/VS_Snippets_CLR_System/system.hashcode.structure/cs/example2.cs
  snippets/csharp/VS_Snippets_CLR_System/system.hashcode.structure/cs/example3.cs
  snippets/csharp/VS_Snippets_CLR_System/system.hashcode.structure/cs/example4.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.hashcode.structure/vb/example1.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.hashcode.structure/vb/example2.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.hashcode.structure/vb/example3.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.hashcode.structure/vb/example4.vb
Labels: :sparkles: 1st-time docs contributor!

#96 port changes - xmldoc
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideDocComments/CS/DocComments.cs
Labels: :file_folder: Repo - samples

#100 Revised example
  snippets/csharp/api/system.Collections/icomparer/reverse.cs
  snippets/visualbasic/api/system.collections/icomparer/reverse.vb
Labels: :file_folder: Repo - samples

#104 ZipArchive updates
  snippets/csharp/VS_Snippets_CLR_System/system.io.compression.ziparchive/cs/program1.cs
  snippets/csharp/VS_Snippets_CLR_System/system.io.compression.ziparchive/cs/program2.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.io.compression.ziparchive/vb/program1.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.io.compression.ziparchive/vb/program2.vb
Labels: :file_folder: Repo - samples, P0

#101 Update Sentiment Analysis Tutorial
  machine-learning/tutorials/SentimentAnalysis/Program.cs
  machine-learning/tutorials/SentimentAnalysis/SentimentAnalysis.csproj
Labels: :construction: Hold for related PR

#116 Correct a typo in comment (comment says "decrypt" but s/be "encrypt")
  snippets/csharp/VS_Snippets_CLR/RijndaelManaged Example/CS/class1.cs
Labels: :file_folder: Repo - samples, :sparkles: 1st-time docs contributor!

#125 Removed unused examples
  snippets/cpp/VS_Snippets_Remoting/IPAddress_Address_AddressFamily/CPP/ipaddress_address_addressfamily.cpp
  snippets/csharp/VS_Snippets_Remoting/IPAddress_Address_AddressFamily/CS/ipaddress_address_addressfamily.cs
  snippets/visualbasic/VS_Snippets_Remoting/IPAddress_Address_AddressFamily/VB/ipaddress_address_addressfamily.vb
Labels: :file_folder: Repo - samples

#139 Correct spelling of "SmtpExamples" namespace
  snippets/csharp/VS_Snippets_Remoting/NCLMailSync/CS/mail.cs
  snippets/csharp/VS_Snippets_Remoting/NclMailASync/CS/mailasync.cs
  snippets/csharp/VS_Snippets_Remoting/NclMailPerms/CS/mailpermissions.cs
  snippets/csharp/VS_Snippets_Remoting/NclSSLMailSync/CS/mail.cs
  snippets/visualbasic/VS_Snippets_Remoting/NclMailASync/vb/mailasync.vb
Labels: :sparkles: 1st-time docs contributor!

#143 Variable name MyStringBuilder -> myStringbuilder
  snippets/cpp/VS_Snippets_CLR/Conceptual.StringBuilder/cpp/example.cpp
  snippets/csharp/VS_Snippets_CLR/Conceptual.StringBuilder/cs/Example.cs
  snippets/visualbasic/VS_Snippets_CLR/Conceptual.StringBuilder/vb/Example.vb
Labels: :file_folder: Repo - samples, :sparkles: 1st-time docs contributor!

#149 fix string interpolation
  snippets/csharp/concepts/linq/how-to-create-a-nested-group_1.cs
  snippets/csharp/concepts/linq/how-to-group-query-results_2.cs
  snippets/csharp/concepts/linq/how-to-group-query-results_3.cs
  snippets/csharp/concepts/linq/how-to-group-query-results_5.cs
  snippets/csharp/concepts/linq/how-to-group-query-results_7.cs
  snippets/csharp/concepts/linq/how-to-group-results-by-contiguous-keys_1.cs
Labels: :sparkles: 1st-time docs contributor!
