Repository dotnet/samples, pull requests merged in 2018-07, with the labels that each got.

#166 Update async-returns1a.cs
  snippets/csharp/programming-guide/async/async-returns1a.cs
Labels: :sparkles: 1st-time docs contributor!

#170 jumped -> jumps
  snippets/csharp/how-to/conversions.zip
  snippets/csharp/how-to/strings.zip
  snippets/csharp/how-to/strings/Concatenate.cs
  snippets/csharp/how-to/strings/ModifyStrings.cs
  snippets/csharp/how-to/strings/ParseStringsUsingSplit.cs
Labels: :file_folder: Repo - samples

#171 Fix "whitespace" words - docs/samples
  framework/docker/MVCRandomAnswerGenerator/MVCRandomAnswerGenerator/Scripts/jquery-1.10.2.intellisense.js
  framework/docker/MVCRandomAnswerGenerator/MVCRandomAnswerGenerator/Scripts/jquery-1.10.2.js
  snippets/cpp/VS_Snippets_CLR/Cryptography.XML.XmlLicenseTransform/cpp/sample.cpp
  snippets/cpp/VS_Snippets_CLR_System/system.Console.WriteLine/CPP/writeline_vararg.cpp
  snippets/cpp/VS_Snippets_CLR_System/system.Security.Cryptography.XML.SignedXml.ComputeSig-Check-KeyedHash-Envelope/CPP/xmldsigenvkeyedhashalg.cpp
  snippets/csharp/VS_Snippets_CLR/Cryptography.XML.XmlLicenseTransform/CS/sample.cs
  snippets/csharp/VS_Snippets_CLR_System/system.DateTimeOffset.ParseExact/cs/ParseExact.cs
  snippets/csharp/VS_Snippets_CLR_System/system.DateTimeOffset.TryParseExact/cs/TryParseExact.cs
  snippets/csharp/VS_Snippets_CLR_System/system.Security.Cryptography.XML.SignedXml.ComputeSig-Check-KeyedHash-Envelope/CS/xmldsigenvkeyedhashalg.cs
  snippets/csharp/VS_Snippets_CLR_System/system.String.TrimEnd/cs/sample.cs
  snippets/csharp/VS_Snippets_CLR_System/system.text.regularexpressions.regex.replace/cs/replaceexample5.cs
  snippets/csharp/VS_Snippets_CLR_System/system.text.regularexpressions.regex.replace/cs/replaceexample6.cs
  snippets/csharp/VS_Snippets_CLR_System/system.text.stringbuilder.chars/cs/chars1.cs
  snippets/csharp/VS_Snippets_CLR_System/system.threading.tasks.parallel.foreach/cs/foreach1.cs
  snippets/csharp/VS_Snippets_Data/xmlprocessingapp/cs/form1.cs
  snippets/csharp/VS_Snippets_Misc/wifissuernameregistry/cs/mvcwepapp/scripts/jquery-1.5.1-vsdoc.js
  snippets/csharp/VS_Snippets_Misc/wifissuernameregistry/cs/mvcwepapp/scripts/jquery-1.5.1.js
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideStrings/CS/Strings.cs
  snippets/csharp/VS_Snippets_WebNet/Samples.AspNet.GeneologyTree/CS/geneologytree.cs
  snippets/csharp/VS_Snippets_WebNet/System.ComponentModel.DataAnnotations2/cs/Customer.cs
  snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlCssParser.cs
  snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlFromXamlConverter.cs
  snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlLexicalAnalyzer.cs
  snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
  snippets/csharp/how-to/strings/ModifyStrings.cs
  snippets/csharp/tutorials/inheritance/base-and-derived.cs
  snippets/csharp/tutorials/inheritance/use-publication.cs
  snippets/fsharp/tour.fs
  snippets/visualbasic/VS_Snippets_CLR/Cryptography.XML.XmlLicenseTransform/VB/sample.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.DateTimeOffset.ParseExact/vb/ParseExact.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.DateTimeOffset.TryParseExact/vb/TryParseExact.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.Security.Cryptography.XML.SignedXml.ComputeSig-Check-KeyedHash-Envelope/VB/xmldsigenvkeyedhashalg.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.String.TrimEnd/vb/sample.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.text.regularexpressions.regex.replace/vb/replaceexample5.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.text.regularexpressions.regex.replace/vb/replaceexample6.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.text.stringbuilder.chars/vb/chars1.vb
  snippets/visualbasic/VS_Snippets_CLR_System/system.threading.tasks.parallel.foreach/vb/foreach1.vb
  snippets/visualbasic/VS_Snippets_Data/xmlprocessingapp/vb/form1.vb
  snippets/visualbasic/VS_Snippets_WebNet/Samples.AspNet.GeneologyTree/VB/geneologytree.vb
Labels: :sparkles: 1st-time docs contributor!

#172 Fix the data type name in the comment
  snippets/fsharp/contour/snippet25.fs
Labels: :sparkles: 1st-time docs contributor!

#175 Fixes divide by zero error
  snippets/csharp/VS_Snippets_Misc/tpldataflow_compositeimages/cs/compositeimages/form1.cs
Labels: :sparkles: 1st-time docs contributor!

#178 Corrected typo in snippet Comment
  snippets/csharp/VS_Snippets_CLR/AddInP1AddInSideAdapters/cs/Calc1ViewToContractAddInSideAdapter.cs
Labels: :sparkles: 1st-time docs contributor!

#196 port change done in inner snippet
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsTypes/CS/keywordsTypes.cs
Labels: verify-build-before-merge
