Repository dotnet/samples, pull requests merged in 2018-04, with the labels that each got.

#10 Renamed sumOfSquares() to squaresOfOdds() in f# unittest samples ...
  core/getting-started/unit-testing-with-fsharp-mstest/MathService.Tests/Tests.fs
  core/getting-started/unit-testing-with-fsharp-mstest/MathService/Library.fs
  core/getting-started/unit-testing-with-fsharp-nunit/MathService.Tests/Tests.fs
  core/getting-started/unit-testing-with-fsharp-nunit/MathService/Library.fs
  core/getting-started/unit-testing-with-fsharp/MathService.Tests/Tests.fs
  core/getting-started/unit-testing-with-fsharp/MathService/Library.fs
Labels: :sparkles: 1st-time docs contributor!

#7 add ref local reassignment
  snippets/csharp/programming-guide/ref-returns/NumberStore.cs
  snippets/csharp/programming-guide/ref-returns/NumberStoreUpdated.cs
  snippets/csharp/programming-guide/ref-returns/Program.cs
  snippets/csharp/programming-guide/ref-returns/ref-returns.csproj
  snippets/csharp/programming-guide/ref-returns/ref-returns1.cs
Labels: :construction: Hold for related PR

#14 update samples for stackalloc
  snippets/csharp/keywords/Program.cs
  snippets/csharp/keywords/StackAllocExamples.cs
  snippets/csharp/keywords/keywords.csproj
Labels: :construction: Hold for related PR

#12 Minor formatting and readability improvements
  snippets/csharp/VS_Snippets_CLR_System/system.Int32.TryParse/cs/TryParse1.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.Int32.TryParse/vb/TryParse1.vb
Labels: :sparkles: 1st-time docs contributor!

#13 Update TryParse sample for readability
  snippets/csharp/VS_Snippets_CLR_System/system.Byte.TryParse/cs/TryParse.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.Byte.TryParse/vb/TryParse.vb
Labels: :sparkles: 1st-time docs contributor!

#23 Typo
  snippets/csharp/VS_Snippets_CLR/GCNotification/cs/Program.cs
Labels: :sparkles: 1st-time docs contributor!

#32 GenericWhereConstraints.cs: fix minor inconsistencies
  snippets/csharp/keywords/GenericWhereConstraints.cs
Labels: :file_folder: Repo - samples

#31 Examples for file names/long file path topic
  snippets/standard/io/file-names/cs/file-refs.cs
  snippets/standard/io/file-names/vb/file-refs.vb
Labels: :file_folder: Repo - samples

#33 Modernized VB type comparison
  snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrOOP/VB/OOP.vb
Labels: :file_folder: Repo - samples
