Repository dotnet/samples, pull requests merged in 2019-07, with the labels that each got.

#1041 Fixed indentation for basicsplitcontainer.cs
  snippets/csharp/VS_Snippets_Winforms/BasicSplitContainer/CS/basicsplitcontainer.cs
Labels: :sparkles: 1st-time samples contributor!

#1047 Add two basic linker samples.
  core/linker/HelloWorldTrimmed/HelloWorldTrimmed.csproj
  core/linker/HelloWorldTrimmed/Program.cs
  core/linker/README.md
  core/linker/TrimmedWithAdditionalRoots/Program.cs
  core/linker/TrimmedWithAdditionalRoots/TrimmedWithAdditionalRoots.csproj
Labels: new-content

#1058 Fix to correct indentation of C# branches and loops
  csharp/branches-quickstart/Program.cs
Labels: :sparkles: 1st-time samples contributor!

#1068 Fix code alignment for creating thumbnail images
  snippets/csharp/VS_Snippets_Winforms/System.Drawing.WorkingWithImages/CS/Class1.cs
Labels: :sparkles: 1st-time samples contributor!

#1069 Indentation and cleanup how-to-create-thumbnail-images
  snippets/csharp/VS_Snippets_Winforms/System.Drawing.WorkingWithImages/CS/Class1.cs
Labels: :sparkles: 1st-time samples contributor!

#1046 Fix areas where const naming conventions were not correctly followed
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideObjects/CS/Objects.cs
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsModifiers/CS/csrefKeywordsModifiers.cs
Labels: :sparkles: 1st-time samples contributor!

#1076 Fixed wrong comment and typo
  snippets/csharp/VS_Snippets_CLR/DPAPI-HowTO/cs/sample.cs
  snippets/visualbasic/VS_Snippets_CLR/DPAPI-HowTO/vb/sample.vb
Labels: :sparkles: 1st-time samples contributor!

#1083 Fix Span<T> Snippets
  snippets/csharp/api/system/span/program.cs
Labels: :sparkles: 1st-time samples contributor!

#1071 Remove unused type samples
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsTypes/CS/dynamic1.cs
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsTypes/CS/keywordsTypes.cs
Labels: :construction: Hold for related PR

#1087 Fixed the formatting issue
  snippets/csharp/VS_Snippets_CLR_System/system.IO.UnmanagedMemoryStream/cs/sample.cs
Labels: :sparkles: 1st-time samples contributor!

#1097 Anonymous methods: removed obsolete snippets
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideDelegates/CS/Delegates.cs
Labels: :construction: Hold for related PR

#1103 Fix code format
  snippets/csharp/VS_Snippets_Winforms/ListViewExample/CS/form1.cs
Labels: :sparkles: 1st-time samples contributor!

#965 Update links
  snippets/csharp/VS_Snippets_Network/RequestDataUsingWebRequest/cs/WebRequestGetExample.cs
  snippets/visualbasic/VS_Snippets_Network/RequestDataUsingWebRequest/vb/WebRequestGetExample.vb
Labels: changes-addressed
