Repository dotnet/samples, pull requests merged in 2019-01, with the labels that each got.

#546 Fix example word
  snippets/csharp/VS_Snippets_CLR_System/system.string.equals/cs/equalsex1.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.string.equals/vb/equalsex1.vb
Labels: :sparkles: 1st-time samples contributor!

#547 replace paths with mydocs variable for how-to-enumerate-directories-and-files
  snippets/csharp/VS_Snippets_CLR_System/system.io.directory.enumeratefiles/cs/program.cs
  snippets/csharp/VS_Snippets_CLR_System/system.io.directoryinfo.enumdirs/cs/program.cs
  snippets/csharp/VS_Snippets_CLR_System/system.io.directoryinfo.enumeratedirectories/cs/program.cs
  snippets/csharp/VS_Snippets_CLR_System/system.io.enumdirs1/cs/program.cs
Labels: changes-addressed

#536 Remove outdated samples
  snippets/csharp/new-in-6/Enrollment.cs
  snippets/csharp/new-in-6/ExceptionFilterHelpers.cs
  snippets/csharp/new-in-6/NetworkClient.cs
  snippets/csharp/new-in-6/Newcode.cs
  snippets/csharp/new-in-6/Program.cs
  snippets/csharp/new-in-6/classList.cs
Labels: :construction: Hold for related PR

#577 Declare variable in correct scope
  snippets/csharp/VS_Snippets_Remoting/System.Net.Sockets.Socket/CS/socket.cs
Labels: :sparkles: 1st-time GH contributor!

#584 Rename method name
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsTypes/CS/keywordsTypes.cs
Labels: :sparkles: 1st-time samples contributor!

#594 Fixed SnippetOutputPrediction Tag
  machine-learning/tutorials/GitHubIssueClassification/Program.cs
Labels: bug, update

#593 Fix typos in snippet comments (#10120)
  snippets/csharp/VS_Snippets_CFX/c_tcpservice/cs/source.cs
  snippets/csharp/VS_Snippets_CFX/c_wshttpservice/cs/source.cs
  snippets/visualbasic/VS_Snippets_CFX/c_tcpservice/vb/source.vb
  snippets/visualbasic/VS_Snippets_CFX/c_wshttpservice/vb/source.vb
Labels: :sparkles: 1st-time GH contributor!

#596 Update to escape1.cs
  snippets/csharp/VS_Snippets_CLR/regularexpressions.language.escapes/cs/escape1.cs
Labels: :sparkles: 1st-time samples contributor!

#599 Added sample
  snippets/csharp/VS_Snippets_CFX/s_uechannels/cs/clientsnippets.cs
Labels: :sparkles: 1st-time samples contributor!

#605 Add unloadability sample
  core/tutorials/Unloading/Host/Host.csproj
  core/tutorials/Unloading/Host/Program.cs
  core/tutorials/Unloading/Host/Properties/launchSettings.json
  core/tutorials/Unloading/Interface/Interface.cs
  core/tutorials/Unloading/Interface/Interface.csproj
  core/tutorials/Unloading/Plugin/Plugin.csproj
  core/tutorials/Unloading/Plugin/PluginClass.cs
  core/tutorials/Unloading/PluginDependency/Logger.cs
  core/tutorials/Unloading/PluginDependency/PluginDependency.csproj
  core/tutorials/Unloading/Unloading.sln
Labels: new-content
