Repository dotnet/samples, pull requests merged in 2019-02, with the labels that each got.

#618 Update concqueue.cs
  snippets/csharp/VS_Snippets_CLR_System/system.collections.concurrent.concurrentqueue/cs/concqueue.cs
Labels: :sparkles: 1st-time samples contributor!

#617 Add snippets for the unloadability doc
  snippets/core/tutorials/unloading/complex_assemblyloadcontext.cs
  snippets/core/tutorials/unloading/create_test_assemblyloadcontext.cs
  snippets/core/tutorials/unloading/execute_and_unload.cs
  snippets/core/tutorials/unloading/execute_method_in_assemblyloadcontext.cs
  snippets/core/tutorials/unloading/simple_assemblyloadcontext.cs
  snippets/core/tutorials/unloading/unload_assemblyloadcontext.cs
  snippets/core/tutorials/unloading/unloadability_issues_example_main.cs
  snippets/core/tutorials/unloading/unloadability_issues_example_test.cs
  snippets/core/tutorials/unloading/wait_for_unload_completion.cs
Labels: new-content

#606 Update program.cs
  snippets/csharp/VS_Snippets_VBCSharp/csprogguidecodingconventions/cs/program.cs
Labels: :sparkles: 1st-time samples contributor!

#627 code changes per try catch freshness review
  snippets/csharp/VS_Snippets_CLR/CatchException/CS/catchexception2.cs
  snippets/visualbasic/VS_Snippets_CLR/CatchException/VB/catchexception2.vb
Labels: changes-addressed

#631 Updated TaxiFarePrediction tutorial to v0.10
  machine-learning/tutorials/TaxiFarePrediction/Program.cs
  machine-learning/tutorials/TaxiFarePrediction/TaxiFarePrediction.csproj
Labels: :construction: Hold for related PR

#632 Update Sentiment Analysis for 0.10.0
  machine-learning/tutorials/SentimentAnalysis/Program.cs
  machine-learning/tutorials/SentimentAnalysis/SentimentAnalysis.csproj
  machine-learning/tutorials/SentimentAnalysis/SentimentData.cs
Labels: :construction: Hold for related PR

#637 Added shift operators snippets
  snippets/csharp/language-reference/operators/Program.cs
  snippets/csharp/language-reference/operators/ShiftOperatorsExamples.cs
Labels: changes-addressed

#643 Removed commented out code from Snippet28
  machine-learning/tutorials/SentimentAnalysis/Program.cs
Labels: :file_folder: Repo - samples

#641 Add demo for Visio automation in .NET Core 3.0
  core/extensions/VisioDemo/Program.cs
  core/extensions/VisioDemo/ReadMe.md
  core/extensions/VisioDemo/VisioDemo.csproj
Labels: :sparkles: 1st-time samples contributor!

#651 Use correct value keyword in set property accessor
  snippets/csharp/VS_Snippets_CLR/conceptual.conversion/cs/iconvertible2.cs
Labels: :sparkles: 1st-time samples contributor!

#669 Extra tab "\t"
  csharp/classes-quickstart/BankAccount.cs
Labels: :sparkles: 1st-time samples contributor!

#675 Add Process.Close
  snippets/csharp/VS_Snippets_CLR/process_refresh/CS/process_refresh.cs
  snippets/visualbasic/VS_Snippets_CLR/process_refresh/VB/process_refresh.vb
Labels: changes-addressed
