Repository dotnet/samples, pull requests merged in 2019-04, with the labels that each got.

#771 Remove unnecessary directives
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsNamespace/CS/csrefKeywordsNamespace2.cs
Labels: :sparkles: 1st-time samples contributor!

#783 Fix typo
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsTypes/CS/dynamic2.cs
Labels: :sparkles: 1st-time samples contributor!

#790 Fixes dotnet/docs#2249
  snippets/csharp/VS_Snippets_Winforms/Classic OpenFileDialog Example/CS/source.cs
Labels: :sparkles: 1st-time samples contributor!

#752 Removed double extern "C" declaration
  core/extensions/DllMapDemo/NewLib.cpp
Labels: :sparkles: 1st-time samples contributor!

#815 Fix copy/paste bug in Roslyn SDK tutorial
  csharp/roslyn-sdk/Tutorials/MakeConst/MakeConst.Test/MakeConstUnitTests.cs
Labels: :sparkles: 1st-time samples contributor!

#822 Update ipaddress.cpp
  snippets/cpp/VS_Snippets_Remoting/System.Net.IPAddress/CPP/ipaddress.cpp
  snippets/csharp/VS_Snippets_Remoting/System.Net.IPAddress/CS/ipaddress.cs
  snippets/visualbasic/VS_Snippets_Remoting/System.Net.IPAddress/VB/ipaddress.vb
Labels: :sparkles: 1st-time samples contributor!

#789 Updated version detection code for .NET Framework 4.8
  snippets/csharp/framework/migration-guide/versions-installed3.cs
  snippets/visualbasic/framework/migration-guide/versions-installed3.vb
Labels: :checkered_flag: Release: .NET Framework 4.8

#842 Update task-returning.cs
  snippets/standard/buffers/memory-t/task-returning/task-returning.cs
Labels: :sparkles: 1st-time samples contributor!

#845 Fix code formatting on snippet 83
  snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.EventExamples/CS/EventExamples.cs
Labels: :sparkles: 1st-time samples contributor!

#838 Migrate TaxiFare sample to 1.0.0-preview
  machine-learning/tutorials/TaxiFarePrediction/Program.cs
  machine-learning/tutorials/TaxiFarePrediction/TaxiFarePrediction.csproj
Labels: :construction: Hold for related PR

#840 Migrate GitHub Issues to 1.0.0-preview
  machine-learning/tutorials/GitHubIssueClassification/GitHubIssueClassification.csproj
  machine-learning/tutorials/GitHubIssueClassification/Program.cs
Labels: signed-off

#857 Managed COM sample for .NET Core 3.0
  core/extensions/COMServerDemo/COMClient/COMClient.csproj
  core/extensions/COMServerDemo/COMClient/Program.cs
  core/extensions/COMServerDemo/COMContract/ContractGuids.cs
  core/extensions/COMServerDemo/COMContract/IServer.cs
  core/extensions/COMServerDemo/COMServer/COMServer.csproj
  core/extensions/COMServerDemo/COMServer/Server.cs
  core/extensions/COMServerDemo/NuGet.config
  core/extensions/COMServerDemo/ReadMe.md
  core/extensions/COMServerDemo/build.proj
  core/extensions/COMServerDemo/global.json
Labels: new-content

#850 Clarify DateTime implicit conversion example
  snippets/csharp/VS_Snippets_CLR_System/system.DateTimeOffset.Operators/cs/Operators.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.DateTimeOffset.Operators/vb/Operators.vb
Labels: :sparkles: 1st-time samples contributor!

#858 Fix exception when sample is built for .NET Core debug.
  snippets/csharp/VS_Snippets_CLR_System/system.runtime.compilerservices.conditionalweaktable.class/cs/example1.cs
Labels: :sparkles: 1st-time samples contributor!

#814 Added SkipLast and TakeLast examples
  snippets/csharp/VS_Snippets_CLR_System/system.Linq.Enumerable/CS/enumerable.cs
  snippets/visualbasic/VS_Snippets_CLR_System/system.Linq.Enumerable/VB/Enumerable.vb
Labels: :sparkles: 1st-time samples contributor!, changes-addressed
