Repository dotnet/samples, pull requests merged in 2019-09, with the labels that each got.

#1389 Update page size values
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt/ExpenseReportPage.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt2/ExpenseItHome.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt2/ExpenseReportPage.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt3/ExpenseItHome.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt3/ExpenseReportPage.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt4/ExpenseItHome.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt4/ExpenseReportPage.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt5/ExpenseItHome.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt5/ExpenseReportPage.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt6/ExpenseItHome.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt6/ExpenseReportPage.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt7/ExpenseItHome.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt7/ExpenseReportPage.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt8/ExpenseItHome.xaml
  snippets/csharp/VS_Snippets_Wpf/ExpenseIt/CSharp/ExpenseIt8/ExpenseReportPage.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt/ExpenseReportPage.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt1_A/ExpenseItHome.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt1_A/ExpenseReportPage.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt2/ExpenseItHome.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt2/ExpenseReportPage.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt3/ExpenseItHome.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt3/ExpenseReportPage.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt4/ExpenseItHome.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt4/ExpenseReportPage.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt5/ExpenseItHome.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt5/ExpenseReportPage.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt6/ExpenseItHome.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt6/ExpenseReportPage.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt7/ExpenseItHome.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt7/ExpenseReportPage.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt8/ExpenseItHome.xaml
  snippets/visualbasic/VS_Snippets_Wpf/ExpenseIt/VB/ExpenseIt8/ExpenseReportPage.xaml
Labels: :sparkles: 1st-time samples contributor!

#1409 Fix the output in threadsafe2a.cs
  snippets/csharp/VS_Snippets_CLR_System/system.threadstaticattribute/cs/threadsafe2a.cs
Labels: :sparkles: 1st-time samples contributor!

#1140 Cleanup AutoMapper usage in SimpleFeedReader
  csharp/tutorials/nullable-reference-migration/finished/SimpleFeedReader.Tests/Services/NewsServiceTests.cs
  csharp/tutorials/nullable-reference-migration/finished/SimpleFeedReader/Services/NewsService.cs
  csharp/tutorials/nullable-reference-migration/finished/SimpleFeedReader/SimpleFeedReader.csproj
  csharp/tutorials/nullable-reference-migration/finished/SimpleFeedReader/Startup.cs
Labels: :sparkles: 1st-time samples contributor!

#1421 Updated the String.Intern example
  snippets/csharp/VS_Snippets_CLR/string.intern/CS/string_intern.cs
  snippets/visualbasic/VS_Snippets_CLR/string.intern/VB/string_intern.vb
Labels: :sparkles: 1st-time samples contributor!

#1419 Update csrefKeywordsModifiers.cs
  snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsModifiers/CS/csrefKeywordsModifiers.cs
Labels: :sparkles: 1st-time samples contributor!

#1435 Add missing whitespace in comments
  snippets/cpp/VS_Snippets_Remoting/SerializationAttributes/CPP/s.cpp
  snippets/csharp/VS_Snippets_Remoting/SerializationAttributes/CS/s.cs
Labels: :sparkles: 1st-time samples contributor!

#1448 Use StreamWriter constructor available on the same targets as the used StreamReader constructor.
  snippets/csharp/VS_Snippets_CLR/StrmReader Ctor1/CS/strmreader ctor1.cs
Labels: :sparkles: 1st-time samples contributor!

#1458 fix typo on hasOffset variable
  winforms/formatting-utility/cs/Form1.cs
Labels: :sparkles: 1st-time samples contributor!

#1380 Dotnet/docs/issues/13680
  async/async-and-await/vb/Application.xaml
  async/async-and-await/vb/Application.xaml.vb
  async/async-and-await/vb/AsyncFirstExampleVB.vbproj
  async/async-and-await/vb/MainWindow.xaml
  async/async-and-await/vb/MainWindow.xaml.vb
  async/async-and-await/vb/readme.md
Labels: :sparkles: 1st-time samples contributor!

#1492 Fix syntax inconsistency
  snippets/csharp/VS_Snippets_CLR_System/system.collections.generic.list.addremoveinsert/cs/program.cs
Labels: :sparkles: 1st-time samples contributor!

#1418 Add parent cs folders to the paths of all the samples used in the Json-DateTime doc
  snippets/standard/datetime/json/csharp/computing-with-jsondocument-error/Program.cs
  snippets/standard/datetime/json/csharp/computing-with-jsondocument-valid/Program.cs
  snippets/standard/datetime/json/csharp/custom-reading-with-utf8jsonreader/Program.cs
  snippets/standard/datetime/json/csharp/custom-writing-with-utf8jsonwriter/Program.cs
  snippets/standard/datetime/json/csharp/datetime-converter-examples/example1/Program.cs
  snippets/standard/datetime/json/csharp/datetime-converter-examples/example1/example1.csproj
  snippets/standard/datetime/json/csharp/datetime-converter-examples/example2/Program.cs
  snippets/standard/datetime/json/csharp/datetime-converter-examples/example2/example2.csproj
  snippets/standard/datetime/json/csharp/datetime-converter-examples/example3/Program.cs
  snippets/standard/datetime/json/csharp/datetime-converter-examples/example3/example3.csproj
  snippets/standard/datetime/json/csharp/deserializing-with-jsonserializer-error/Program.cs
  snippets/standard/datetime/json/csharp/deserializing-with-jsonserializer-valid/Program.cs
  snippets/standard/datetime/json/csharp/reading-with-utf8jsonreader-error/Program.cs
  snippets/standard/datetime/json/csharp/reading-with-utf8jsonreader-valid/Program.cs
  snippets/standard/datetime/json/csharp/serializing-with-jsonserializer/Program.cs
  snippets/standard/datetime/json/csharp/writing-with-utf8jsonwriter/Program.cs
Labels: :construction: Hold for related PR

#1529 BufferWidth resize approach.
  snippets/csharp/VS_Snippets_CLR_System/system.console.windowleft/cs/windowleft1.cs
Labels: :sparkles: 1st-time samples contributor!

#1531 change nullable elements
  csharp/tutorials/nullable-reference-migration/finished/SimpleFeedReader.Tests/SimpleFeedReader.Tests.csproj
Labels: P0

#1561 Correct GetEnvVariable logic for AsyncStreams tutorial
  csharp/tutorials/AsyncStreams/finished/IssuePRreport/IssuePRreport/Program.cs
  csharp/tutorials/AsyncStreams/start/IssuePRreport/IssuePRreport/Program.cs
Labels: :sparkles: 1st-time samples contributor!

#1559 Fix No Answer Inference
  csharp/NullableIntroduction/NullableIntroduction/SurveyResponse.cs
Labels: :sparkles: 1st-time samples contributor!
