Repository dotnet/samples, pull requests merged in 2019-03, with the labels that each got.

#685 Updated csproj file to make the samples work
  windowsforms/datagridview/CSWinFormDataGridView/CSWinFormDataGridView.csproj
  windowsforms/datagridview/CSWinFormDataGridView/Program.cs
  windowsforms/helloworld-sharedsource/CoreWindowsFormsApp/CoreWindowsFormsApp.csproj
Labels: :sparkles: 1st-time samples contributor!

#687 add missing snippet
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideStrings/CS/TestStringBuilder.cs
Labels: migration-fixes

#691 Add MovieRecommender tutorial sample
  machine-learning/tutorials/MovieRecommendation.sln
  machine-learning/tutorials/MovieRecommendation/MovieRatingData.cs
  machine-learning/tutorials/MovieRecommendation/MovieRecommendation.csproj
  machine-learning/tutorials/MovieRecommendation/Program.cs
Labels: :construction: Hold for related PR

#680 Update dataset usage and to version 0.11 for Sentiment Analysis
  machine-learning/tutorials/SentimentAnalysis/Program.cs
  machine-learning/tutorials/SentimentAnalysis/SentimentAnalysis.csproj
  machine-learning/tutorials/SentimentAnalysis/SentimentData.cs
Labels: :construction: Hold for related PR

#690 Upgraded TaxiFarePrediction solution to v0.11
  machine-learning/tutorials/TaxiFarePrediction/Program.cs
  machine-learning/tutorials/TaxiFarePrediction/TaxiFarePrediction.csproj
  machine-learning/tutorials/TaxiFarePrediction/TaxiTrip.cs
Labels: :construction: Hold for related PR

#692 Migrated GitHubLabeler to v0.11
  machine-learning/tutorials/GitHubIssueClassification/GitHubIssueClassification.csproj
  machine-learning/tutorials/GitHubIssueClassification/Program.cs
Labels: :construction: Hold for related PR

#701 Updated event dictionary example
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideEvents/CS/Events.cs
Labels: :construction: Hold for related PR

#713 Sample output from 2007 to 2006
  snippets/csharp/VS_Snippets_CLR_System/system.TimeZone2.Conversions/cs/System.TimeZone2.Conversions.cs
Labels: :sparkles: 1st-time samples contributor!

#694 Migrated IRISClustering to v0.11
  machine-learning/tutorials/IrisFlowerClustering/IrisFlowerClustering.csproj
  machine-learning/tutorials/IrisFlowerClustering/Program.cs
Labels: :construction: Hold for related PR

#724 Fix method name typo
  snippets/csharp/tuples/tuples/Statistics.cs
Labels: :sparkles: 1st-time samples contributor!

#733 Adding VB version
  snippets/visualbasic/VS_Snippets_Remoting/NclSslClientSync/VB/clientsync.vb
Labels: :sparkles: 1st-time samples contributor!

#735 VB sample added
  snippets/visualbasic/VS_Snippets_Remoting/NclSslServerSync/VB/serversync.vb
Labels: :sparkles: 1st-time samples contributor!

#748 Removed not used snippets
  snippets/csharp/language-reference/operators/DecrementAndIncrementExamples.cs
  snippets/csharp/language-reference/operators/DivisionExamples.cs
  snippets/csharp/language-reference/operators/RemainderExamples.cs
Labels: :construction: Hold for related PR

#668 Add DllMap sample
  core/extensions/DllMapDemo/Demo.cs
  core/extensions/DllMapDemo/Demo.csproj
  core/extensions/DllMapDemo/Demo.xml
  core/extensions/DllMapDemo/Map.cs
  core/extensions/DllMapDemo/NewLib.cpp
  core/extensions/DllMapDemo/ReadMe.md
Labels: blocked

#749 typo: hander -> handler
  snippets/csharp/VS_Snippets_CFX/s_ueexceptionhandler/cs/program.cs
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideDelegates/CS/Delegates.cs
  snippets/csharp/VS_Snippets_VBCSharp/csvariance/cs/form1.cs
  snippets/csharp/VS_Snippets_Wpf/CommandingOverviewSnippets/CSharp/Window1.xaml.cs
  snippets/visualbasic/VS_Snippets_CFX/s_ueexceptionhandler/vb/module1.vb
  snippets/visualbasic/VS_Snippets_CLR/portableclasslibrarymvvm/vb/relaycommand.vb
  snippets/visualbasic/VS_Snippets_VBCSharp/csvariance/vb/form1.vb
  snippets/visualbasic/VS_Snippets_Wpf/CommandingOverviewSnippets/visualbasic/window1.xaml.vb
Labels: changes-addressed
