Repository dotnet/samples, pull requests merged in 2019-05, with the labels that each got.

#861 Update FileIteration.cs
  snippets/csharp/VS_Snippets_VBCSharp/csFilesAndFolders/CS/FileIteration.cs
Labels: :sparkles: 1st-time samples contributor!

#830 Add ProductSalesAnomalyDetection
  machine-learning/tutorials/ProductSalesAnomalyDetection.sln
  machine-learning/tutorials/ProductSalesAnomalyDetection/ProductSalesAnomalyDetection.csproj
  machine-learning/tutorials/ProductSalesAnomalyDetection/ProductSalesData.cs
  machine-learning/tutorials/ProductSalesAnomalyDetection/Program.cs
Labels: :construction: Hold for related PR

#875 Update source.cs
  snippets/csharp/VS_Snippets_ADO.NET/Classic WebData SqlCommand Example/CS/source.cs
Labels: :sparkles: 1st-time samples contributor!

#883 Updated method name to use .NET naming guidelines
  snippets/csharp/VS_Snippets_Remoting/System.Net.IPAddress.Parse/CS/parse.cs
Labels: :sparkles: 1st-time samples contributor!

#894 Code is wrongly formatted for HtmlElementInsertionOrientation Enum
  snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.HtmlElement/CS/Form1.cs
Labels: :sparkles: 1st-time samples contributor!

#903 Formatting of try-catch
  snippets/csharp/VS_Snippets_CLR_System/system.aggregateexception.class/cs/exception1.cs
Labels: :sparkles: 1st-time samples contributor!

#914 RegFree COM example
  core/extensions/COMServerDemo/COMClient/COMClient.csproj
  core/extensions/COMServerDemo/COMClient/COMClient.manifest
  core/extensions/COMServerDemo/COMServer/COMServer.csproj
  core/extensions/COMServerDemo/ReadMe.md
Labels: :file_folder: Repo - samples

#919 Correct comment indentation for DrawItemEventHandler Delegate C# example
  snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.MenuItemOwnerDraw/CS/form1.cs
Labels: :sparkles: 1st-time samples contributor!

#931 Fix Typo in Tutorial Project
  csharp/tutorials/AsyncStreams/finished/IssuePRreport/IssuePRreport/Program.cs
  csharp/tutorials/AsyncStreams/start/IssuePRreport/IssuePRreport/Program.cs
Labels: :sparkles: 1st-time samples contributor!
