Repository dotnet/samples, pull requests merged in 2020-02, with the labels that each got.

#1945 Remove redundant null checks.
  snippets/csharp/tutorials/inheritance/base-and-derived.cs
Labels: :sparkles: 1st-time samples contributor!

#2017 Change interface method names to pascal case
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideInheritance/CS/Inheritance.cs
Labels: :sparkles: 1st-time samples contributor!

#1999 Remove old samples no longer used in C# programming guide.
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideIndexers/CS/Indexers.cs
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideInheritance/CS/Inheritance.cs
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideObjects/CS/Objects.cs
  snippets/csharp/VS_Snippets_VBCSharp/csProgGuideProperties/CS/Properties.cs
Labels: :construction: Hold for related PR

#2008 Added snippets for the struct article
  csharp/language-reference/builtin-types/Program.cs
  csharp/language-reference/builtin-types/StructType.cs
Labels: changes-addressed
